[book]
authors = ["Kevin Delfour"]
language = "fr"
src = "src"
title = "Etre CTO ..."
description = "Un guide collaboratif écrit par des CTOs pour partager leur expérience avec ceux qui aspirent à ce rôle ou qui débutent. L'approche se veut pratique et humaine, mêlant conseils opérationnels et retours d'expérience authentiques."

[output.html.playground]
editable = true
line-numbers = true

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2