[book]
authors = ["Kevin Delfour"]
language = "fr"
src = "src"
title = "To be or not to be... a CTO"
description = "Un guide collaboratif écrit par des CTOs pour partager leur expérience avec ceux qui aspirent à ce rôle ou qui débutent. L'approche se veut pratique et humaine, mêlant conseils opérationnels et retours d'expérience authentiques."
repository = "https://github.com/kdelfour/Ebook_To_be_Or_not_to_be_CTO"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
theme = "theme"
smart-punctuation = true
mathjax-support = false
copy-fonts = true
default-theme = "latte"
preferred-dark-theme = "mocha"
additional-css = ["theme/catppuccin.css", "theme/catppuccin-admonish.css", "theme/pagetoc.css", "theme/navigation.css"]
additional-js = ["mermaid.min.js", "mermaid-init.js", "theme/pagetoc.js", "theme/navigation.js", "theme/pwa.js"]
copy-files = ["theme/manifest.json", "theme/sw.js", "theme/offline.html"]

[output.html.playground]
editable = true
line-numbers = true

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2
